### ISSUE TITLE
Question: Does this library allow for logging of operations in HA?

### ISSUE THREAD

**Issue by TheFiZi** [chamberlain2007/pyaprilaire#13]
I'm looking at getting one of these thermostats and I don't think the Aprilaire App for iOS/Android shows and kind of historical information around the operation of the HVAC system.

Using this library with Home Assistant, does it log when stage 1/2 heating/cooling, humidification and dehumidification is run?

**Comment by TheFiZi** [comment]
Ah, I found your other repo and read the README <https://github.com/chamberlain2007/aprilaire-ha#supported-functionality>

Looks like the answer to this question is "Yes".

**Comment by chamberlain2007** [comment]
@TheFiZi Everything you specified is supported with the exception of separate stage 1/2 heating and cooling, you would just see that as heating or cooling on the sensor in the HVAC action. The data is available for that, but it's not exposed granularly at this time.

Please note that the Aprilaire integration is now merged into the main Home Assistant, with the exception of the sensors which are currently being worked on merging in. Check back in the next few releases and once the sensors are in, there's no reason to use the HACS version.
