### ISSUE TITLE
add support for outdoor temperature broadcast

### ISSUE THREAD

**Issue by jonoberheide** [chamberlain2007/pyaprilaire#18]
Hi Matthew! Thanks for your support of this library/HA component.

I was hoping to add support for broadcasting an outdoor temperature from HA to the 8840 thermostats, which is apparently supported via the automation protocol. This enables some handy features like an auto mode for humidification.

Any ideas on this front? I'm not sure where any protocol documentation exists for the Aprilaire automation protocol.

**Comment by chamberlain2007** [comment]
@jonoberheide FYI I can do this easily here at the library level, but it will take longer for it to be accepted into Home Assistant. Expect it to take at least 1 or 2 releases before you see it there due to their dev cycle.

**Comment by jonoberheide** [comment]
Nice, that was fast!

What's the best way to expose that on the HA side? An HA service/action that can call that function to update the outdoor temp?

**Comment by chamberlain2007** [comment]
There will be a number entity whose value you can read and write to.

**Comment by jonoberheide** [comment]
Makes sense!

--
Jon Oberheide ***@***.***>

**Comment by chamberlain2007** [comment]
Bad news, I won't be able to proceed with this as it turns out my thermostat doesn't support this so I can't test against a real device :( I have a branch here if you want to get HA running locally and try it out and see if it works. https://github.com/chamberlain2007/core/tree/aprilaire-written-outdoor-temperature-value

**Comment by jonoberheide** [comment]
Yep, will give it a test.

**Comment by jonoberheide** [comment]
@chamberlain2007 Looks like it works:

![Screenshot 2024-12-17 1 24 44 PM](https://github.com/user-attachments/assets/7933a772-1c99-45fe-8a48-be5a773e4814)

![PXL_20241217_182525256](https://github.com/user-attachments/assets/1f8144f6-208b-46c6-ad9c-72367d0ae37f)

Strangely, the entity is labeled with a "none" suffix and doesn't seem to be adjustable from the entity popup, but it works on the main device page:

![Screenshot 2024-12-17 1 19 30 PM](https://github.com/user-attachments/assets/d7dc1b0d-5853-4149-acd3-e1cf62050b48)
