### ISSUE TITLE
RFE: add support for S86WMUPR

### ISSUE THREAD

**Issue by jonoberheide** [chamberlain2007/pyaprilaire#23]
More of a RFE than an issue. See: https://community.home-assistant.io/t/add-aprilaire-support-for-s86w-thermostats/786086

I added a S86WMUPR using the existing integration and...it kind of works? It adds a device to HA, but doesn't seem to be reading sensors or receiving status updates. Happy to ship you a unit?

![image](https://github.com/user-attachments/assets/f35a4a78-cb30-4164-82b4-be5995ee0c14)

**Comment by chamberlain2007** [comment]
If you have a unit to spare that would help a lot in debugging.

From your screenshot it looks like the status values are probably saying not installed, which means we don't expose the sensor entities to HA. 

![image](https://github.com/user-attachments/assets/bf7942e2-c004-47c1-82f4-8fbca3d04c34)

Do you have an actual sensor installed? If there isn't one installed, it won't be there as an entity.

If you have a local instance running you can breakpoint and look at the coordinator.data for key indoor_humidity_controlling_sensor_status and check if it is 0. My expectation is that it's probably 3 (not installed).

Shoot me an email if you want to send a unit at mattfitzgeraldchamberlain@proton.me and I can take a look, but I'm not an HVAC person so I can really only look at what the data it sends is.

**Comment by chamberlain2007** [comment]
Few issues here which have been addressed in a PR for Home Assistant https://github.com/home-assistant/core/pull/133974. Issues were that the S86WMUPR doesn't have a name and doesn't report all statuses when connected to, they must be read manually. I'm going to close this issue as it doesn't belong to pyaprilaire. In the future open the issue in the Home Assistant repo please.

**Comment by jonoberheide** [comment]
Very cool, thanks!
